<?php

namespace Database\Seeders;

use App\Customer;
use Flynsarmy\CsvSeeder\CsvSeeder;
use Illuminate\Support\Facades\DB;

class CustomersTableSeeder extends CsvSeeder
{
    public function __construct()
	{
		$this->table = 'customers';
		$this->insert_chunk_size = 300;
		$this->filename = base_path().'/database/seeders/csvs/customers/ICAO-codes-Oct-19.csv';
		$this->offset_rows = 1;
		$this->mapping = [
    		1 => 'company_name',
            5 => 'icao'
		];
		$this->should_trim = true;
	}
    
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
	{
		// Recommended when importing larger CSVs
		DB::disableQueryLog();

		// Uncomment the below to wipe the table clean before populating
		DB::table($this->table)->truncate();
		
		parent::run();
		
		DB::table('customers')->insert([
    		['company_name' => 'Rolls Royce', 'icao' => 'ZZZZZ'],
            ['company_name' => 'LHT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CESSNA', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Fokker Service B.V.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'UTC Aerospace Systems', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Hamilton Sundstrand', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Air France Industries', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Pratt & Whitney', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Rosemount Aerospace', 'icao' => 'ZZZZZ'],
            ['company_name' => 'A J Walter', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EMBRAER', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SR Technics', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Nord-Micro GmbH & Co. OHG', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MTU MAINTENANCE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Airbus', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AMECO BEIJING', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ST Aerospace', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GULFSTREAM', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Safran', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SAESL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HAESL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Woodward, Inc.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AAR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Dassault', 'icao' => 'ZZZZZ'],
            ['company_name' => 'P&W EAGLE SERVICES ASIA', 'icao' => 'ZZZZZ'],
            ['company_name' => 'N3 ENGINE OVERHAUL SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CHRISTCHURCH ENGINE CENTRE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Textron', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GE CELMA', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Proponent', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TURBINE SERVICES & SOLUTIONS AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Boeing', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Turkish Technic', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HAECO', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ATC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BAE Systems', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Avtrade', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Zodiac', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Barfield', 'icao' => 'ZZZZZ'],
            ['company_name' => 'STANDARDAERO', 'icao' => 'ZZZZZ'],
            ['company_name' => 'IHI Corporation', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Leonardo', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Bombardier', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ANA Trading', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HEICO Component Repair Group', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Triumph', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Vector Aerospace', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ABX', 'icao' => 'ZZZZZ'],
            ['company_name' => 'L-3 communications', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION AVIONICS & INSTRUMENTS CO.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'IAI', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GA Telesis', 'icao' => 'ZZZZZ'],
            ['company_name' => 'E M S', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MARCH AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'IPECO, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'COMPANIA PANAMENA DE AVIACION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GEAM, TX HEADQUARTERS & WAREHS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ADJUSTMENTQTM_US', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SIA ENGINEERING COMPANY LTD.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GLOBAL PARTS INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Unical Aviation', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SAAB', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JALUX INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRMARK INTERNATIONAL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Magellan', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FATAIR INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Global Aviation Technical', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TARA AIR PVT LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROTRON AIRPOWER INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AerSale', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Aerospares 2000 LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DUNCAN AVIATION, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MTU engines', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Wichita Service Center', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ABU DHABI AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GECAS ASSET MANAGEMENT SERVICE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'OEMServices', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Sabena Technics', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GLOBAL AIRTECH', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROTRON, LTD.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Aero-Zone', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Precision Heliparts', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AERO CONTROLS INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WILLIS AERONAUTICAL SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AMAC AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TURBO RESOURCES INTL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVGROUP', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Kellstrom', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BABCOCK MISSION CRITICAL SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HONEYWELL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PRECISION MATERIALS & LOGISTICS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'LTR PTE LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CORPORATE JET SUPPORT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIR METHODS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TRADE AIR AIRLINE SUPPORT LTD.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CRS JET SPARES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Sikorsky', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JSC <<ABRIS>>', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JAPAN AERO PRESSURE CO., LTD.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AAE, LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'STANDARDAERO ALLIANCE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ATR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'OAKENHURST AIRCRAFT SERVICES LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PRECISION ACCESSORIES & INSTRU', 'icao' => 'ZZZZZ'],
            ['company_name' => 'LEGION AERO, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WALMART AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JET PARTS, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Aviall', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TSI AVIATION, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'VISION AERO', 'icao' => 'ZZZZZ'],
            ['company_name' => '25 REPAIR CENTRE LIMITED', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Aramco Overseas company BV', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TOTAL AIRCRAFT SUPPORT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DMS Enterprise GmbH', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ALLIANCE AEROSPACE GROUP, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'INFLITE THE JET CENTRE LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => '1st Choice Aerospace', 'icao' => 'ZZZZZ'],
            ['company_name' => 'RUAG', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PROFESSIONAL TECHNOLOGY REPAIR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'VAS AERO', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MID CONTINENT AVIATION SERVICES, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TURKISH AEROSPACE INDUSTRIES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PATS AIRCRAFT LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SENTRY AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Mach 2', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TAIKOO ENGINE SERVICES (XIAMEN)', 'icao' => 'ZZZZZ'],
            ['company_name' => 'KF AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Larson Cando Inc', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AV GROUP/ATLANTA', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIR-CERT INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GLOBAL AVIATION LEASING INC', 'icao' => 'ZZZZZ'],
            ['company_name' => '2WINGS AIRCRAFT PARTS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TrueAero, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Zenith Aviation Limited', 'icao' => 'ZZZZZ'],
            ['company_name' => 'METRO AVIATION, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SKYTECH AIRCRAFT ENGINEERING LIMITED', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CONSTANT AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'RBR MAINTENANCE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CJ AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Wesco Manufacturing Inc', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION INVENTORY RESOURCES INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AERFIN LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'NETJETS AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SUPPORT AIR, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'IMP GROUP LTD.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION ASSET TRADING LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => '3GEN AVION TRADING', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVAIR AERO', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Western Aircraft, Inc.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'S3 INTERNATIONAL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ANSETT AIRCRAFT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SHEY SYSTEMS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EASTWEST AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'REGIONAL ONE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Honda Aircraft Company, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FAA FEDERAL AVIATION ADMINISTRATION', 'icao' => 'ZZZZZ'],
            ['company_name' => '328 SUPPORT SERVICES GMBH', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CTS ENGINES, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ALPINE AIR SUPPORT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Allaero', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Touchdown Aviation', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SUKHOI CIVIL AIRCRAFTS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SOUTHSTAR AIRCRAFT INTERIORS, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION PARTS & SUPPLY INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION CONCEPTS INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JET MIDWEST, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BAYVIEW AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WORTHINGTON AVIATION PARTS, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SAMCO AIRCRAFT MAINTENANCE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ZINA FLIGHT SUPPORT LLC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GENX PROGRAM', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ALE SERVICE CENTER, S. DE R.I. DE C.V.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'L & M AIRCRAFT PARTS, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'UNITED AERO GROUP, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MERRITT AVIATION INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TP AEROSPACE PRO APS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRCRAFT SYSTEMS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HINDUSTAN AERONAUTICS LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ALBERTH AIR PARTS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FLIGHT SAFETY INTERNATIONAL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SHORELINE MARINE DBA SAFETECH', 'icao' => 'ZZZZZ'],
            ['company_name' => '3 POINTS AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Mitchell', 'icao' => 'ZZZZZ'],
            ['company_name' => 'KG Aircraft Rotables Co., LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HELIPONENTS INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SIMCOM ORLANDO', 'icao' => 'ZZZZZ'],
            ['company_name' => 'STS Component Solutions', 'icao' => 'ZZZZZ'],
            ['company_name' => 'C & L AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MIDAMERICAN AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'INTERNATIONAL FLIGHT MANAGEMENT INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Aerospace Engineering Group S.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'IDEAL C.W.S. TRADEX INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GIE Avions De Transport Regional', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TransCanada Turbines', 'icao' => 'ZZZZZ'],
            ['company_name' => 'KING AEROSPACE INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'QWEST AIR PARTS INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROSPACE ASSET TRADING', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PENTASTAR AVIATION, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CORPORATE EAGLE MANAGEMENT SERVICES INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CTS-COMPLETE TURBINE SERVICE, LLC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DELTA AVIATION, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AREVA NP INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BF AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'KENN BOREK AIR LTD.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Aero Vision Aircraft Services', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Artemis Aerospace Ltd', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EAST AIR CORPORATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ROCKWELL COLLINS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Aventure Aviation', 'icao' => 'ZZZZZ'],
            ['company_name' => 'NORTH BAY AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'NEW GEN AEROSPACE CORPORATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GFD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Next Level Aviation', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HI FLY AERO', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Aero-Link Arizona', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Regional Airline Support Group', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CAE INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Alaris Aerospace Systems LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WESTJET ENCORE, LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Max Lehner & Co AG', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ACS AVIATION LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROKOOL AVIATION CORPORATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MAC AEROSPACE CORPORATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SILK WAY HELICOPTERS SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Aviation Resources, Inc.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EUROPAVIA ESPANA S.A.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Saywell International', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CONAGRA FOODS, IIN', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CONSOLIDATED AIRCRAFT SUPPLY', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRCO, LLC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TEAM AERO LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GREAT LAKES GLOBAL AVIATION LOGISTICS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JET REPAIR CENTER', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AFRICAIR, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'UNIVERSAL ASSET MANAGEMENT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ITS Infinity Trading', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MAVERICK HELICOPTERS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION MAINTENANCE GMBH', 'icao' => 'ZZZZZ'],
            ['company_name' => 'LOCKHEED MARTIN', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WERNER AERO SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PHI, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVMAX AVIATION SERVICES ,INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WING CONTROL COMPONENT SOLUTIONS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ZIMEX AVIATION LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ROCKY MOUNTAIN AIRCRAFT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'NOVO AERO COMPONENTS LLC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'IFL GROUP, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRPRO AVIATION AIRLINE SUPPORT, IN', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AERO ASSETS, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ENGIE INEO', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIR TRANSPORT INTERNATIONAL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIR NORTH LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Mel Aviation', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PEGASUS TECHNOLOGIES INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'APS Air Parts', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MED-AIR, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TPS AVIATION INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'KAREN SA', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRCRAFT CUSTOM INTERIORS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AERO DIRECT, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FOURWINDS AVIATION, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HELIDAX SAS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CENTRAL COPTERS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'NORTHERN WINGS REPAIR, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AERONAUTIC INVESTMENTS, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MOUNTAIN AEROSPACE, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CANADIAN NORTH INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'COMAV ASSET MANAGEMENT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MAXCRAFT AVIONICS LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AERO INDUSTRIES PTE  LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EXCEL AEROSPACE, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JETCALL GMBH & CO KG', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EUROPEAN AVIATION LIMITED', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FLEXJET', 'icao' => 'ZZZZZ'],
            ['company_name' => 'VAS AERO SERVICES, LLC (CONSIGNMENT)', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AURIC AVIONICS & INSTRUMENTS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'RED STAR HAVACILIK HIZMETLERI', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FLIGHT AEROTECH LLC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CURTISS-WRIGHT CONTROLS ELECTRONIC SYSTEMS, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MARYLAND STATE POLICE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GLOBAL AIRSERVICES, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'INTERTRADE LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'COMPONENT SERVICES PROGRAM', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BROWARD AVIATION SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WOODWARD HRT, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SUMMIT AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DO-TEC GMBH', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FLIGHT LOGISTICS GROUP', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Total Aviation Ltd A/S', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Eaton', 'icao' => 'ZZZZZ'],
            ['company_name' => '', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ELITE JET SOLUTIONS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'LLOYD USA INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TRADE-AIR INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'INTERIOR DEVELOPMENT GROUP, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HELICOPTER EXPRESS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'L.J. WALCH CO INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GAR-MRO-Services, Inc.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TRINITY AIRCRAFT PARTS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'M7 AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CONAIR GROUP, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'UNITED AEROSPACE CORPORATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DIVERSIFIED AERO SERVICES, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRMARK INTERNATIONAL REPAIR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ITS ENTERPRISE CORP D/B/A SOURCE AMERICA', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FB HELISERVICES LIMITED', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AV INDUSTRIES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRMARK COMPONENTS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FLIGHTPATH SERVICES, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PT. Garuda Indonesia (Persero)', 'icao' => 'ZZZZZ'],
            ['company_name' => 'NORDAM GROUP', 'icao' => 'ZZZZZ'],
            ['company_name' => 'UNICAL DEFENSE, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'RATIER FIGEAC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AUSTRAL LINEAS AEREAS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Jet Engine Solutions LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ASPEN HELICOPTERS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Reef Aviation Group', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Reliance Aircraft International', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SOUTH FLORIDA JET CENTER', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVENTURE INTERNATIONAL AVIATION SVCS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIR START REGIONAL SPARES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MJ AIRCRAFT, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PAI CANADA INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GLOBAL AVIATION RESOURCES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HAWKER BEECHCRAFT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JAS AIRCRAFT SALES AND LEASING', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SHELL AEROSPACE SUPPLIES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CASCADE SPARES, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Bel Air Aviation A/S', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BASIN AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DELTA MATERIAL SERVICES, LLC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GKN', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PRECISION AERO TECHNOLOGY', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PAE AVIATION AND TECHNICAL SERVICE LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PRIME INDUSTRIES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'IRISH AIR CORPS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ELLINAIR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'O&S AVIATION SRL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GAMIT LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HELICENTRO LIMITADA', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HELI-MART, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => '3 TOP AVIATION SERVICES LTD`', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION ASSISTANCE GMBH', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Short Brothers Plc', 'icao' => 'ZZZZZ'],
            ['company_name' => 'LIGHTNING AIR SPARES, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Meggitt Akron', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Meggitt Avrille', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Meggitt Birmingham', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Meggitt Coventry', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Meggitt Fribourg', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Meggitt Loughborough', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Meggitt McMiville', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Meggitt Miami', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Meggitt NASCO', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Meggitt North Hollywood', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Meggitt Orange County', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Meggitt Singapore', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Meggitt Ventura County', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SKYDIVE DUBAI LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MEXICANA MRO S.A. DE C.V.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CALJET INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AERO CONSULTING & TRADING COMPANY', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DASI', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AAI AERO, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MTI Aviation, Inc.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Jetset Aerospace Inc', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROSERVICES LIMITED', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FLORIDA JET PARTS, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'REGENT AEROSPACE CORP.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AMERICAN AVIATION, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIR & GROUND AVIATION LTD.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HELI AIR SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ROTAK HELICOPTER SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'RAINER HELI INTERNATIONAL, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WORLD CLASS AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EUROTRADIA INTERNATIONAL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'NORDIC AVIATION GROUP', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROVISION AIRCRAFT SERVICES LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TEAM JAS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JETT AIRCRAFT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SURIPARTS CORP.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SKY MART SALES CORP.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PENAIR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIR PARTS SERVICES & SUPPLIES LTD.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIA SOURCE, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GLOBAL AVIATION CO', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AvMax Aviation Services Inc.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ACCENT AIR, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FALCON DYNAMICS, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DOW AERO LOGISTICS, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVION SYSTEMS INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'KONAIR S.A.U.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SUMMIT AIR CHARTERS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'STERLING HELICOPTER', 'icao' => 'ZZZZZ'],
            ['company_name' => 'NEDAERO COMPONENTS B.V.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Z.G.A. AIRCRAFT PARTS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ATLAS AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'RJ CORMAN RAILROAD GROUP, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FR AVIATION LIMITED', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Ex-Change Parts AB', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Siemens', 'icao' => 'ZZZZZ'],
            ['company_name' => 'H & B AVIATION LC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CASP AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'L\'HOTELLIER/KIDDE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'OTTO INSTRUMENT SERVICE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HAWK AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GLOBAL PARTS SUPPORT, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JOHN CAMERON AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DONCASTER CITATION SERVICE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'OH CAPITAL ASSETS, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Cogsys Limited t/a DNV GL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ATLANTIC JET SUPPORT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CHINA INVENTORY GROUP', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROTOP TAXI AEREO LTDA', 'icao' => 'ZZZZZ'],
            ['company_name' => 'M W HELICOPTERS LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FORMAT AEROSPACE, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HAWK AVIATION LA LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'UNICORP SYSTEMS INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EXECUTIVE JET SUPPORT LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MAYO AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DAHER SOCATA S.A.S.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WARBELOW\'S AIR VENTURES, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TRADE-AIR UK Ltd', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Aesse Misure S.r.l.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BLUE HAWAIIAN HELICOPTERS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Air Support', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SKYWAYS TECHNICS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'KELLSTROM REPAIR SERVICES INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'D & D ENTERPRISES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JET ACCESSORY CENTER', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CONTINENTAL AIRCRAFT SUPPORT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BROAD RIVER AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROTRADE LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JET TECH INTERNATIONAL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EXTREME AVIATION SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SKYLINE AVIATION SUPPLIES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TRITEX CORPORATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JET INTERNATIONAL CO LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MIAMI NDT INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TURBO AIR, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MORNINGSTAR AIR EXPRESS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AERONAUTICAL SUPPORT INT\'L., LLC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SEDA AEROSPACE LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MASCO SERVICE CORPORATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Starfish PPS, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CRANFIELD AEROSPACE SOLUTIONS LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'XTREME AVIATION SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BA CityFlyer Limited', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JAPAN AEROSPACE CORPORATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ASSET CONVERSION SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRCRAFT TRADING, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JET AVIATION ASIA PACIFIC PTE LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GE OWS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EFTEC LIMITED', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GLOBAL AVIATION SYSTEMS INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SALT RIVER AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'REPMAN CO. LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GREENPOINT TECHNOLOGIES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BAKER AVIATION LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MARTINAIRE AVIATION, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION SERVICES OF AMERICA', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HELICOPTERS ITALIA S.R.L', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TIFFIN AIRE INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'COMMUTER SPARES INTERNATIONAL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'D4Vib, Unipessoal Lda.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'B & V AIRCRAFT PARTS & SUPPLY', 'icao' => 'ZZZZZ'],
            ['company_name' => 'S&K TECHNOLOGIES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ISTEC INTERNATIONAL B.V.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HONG KONG EXPRESS AIRWAYS LIMITED', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HELIJET INTERNATIONAL INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATECA S.A.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'UNITED ENTERPRISE GROUP', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CARSONAIR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MSI GmbH & Co KG', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Stevens Aviation', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AV-AIR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ABS JETS A.S', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DK TURBINES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRDOGS SUPPLIES, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROTRENDS AVIATION (M) SDN BHD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'American General Supplies', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Lotnicze Pogotowie Ratunkowe', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Standard Aero', 'icao' => 'ZZZZZ'],
            ['company_name' => 'KAAN AIR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CAE AVIATION TRAINING SOLUTIONS, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'VHL AIRCRAFT INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Applied Aerospace Solutions', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MTI Instruments', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WORLDWIDE AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'QUEST AVIATION. INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GATS (GLOBAL AVIATION TECHNICAL SOLUTIONS S.E.C.S)', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AERO PRECISION INDUSTRIES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'VELO AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SUNSHINE HELICOPTERS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'InTech Aerospace Service', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HAWK AVIATION LTD.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TOPCAST AVIATION SERVICES LIMITED', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Mitsubishi Hitachi Power Syste', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIC-COMAC Shanghai AMC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TUNISAIR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TAYSIDE AVIATION LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => '2 EXCEL ENGINEERING LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PLEXUS MANUFACTURING SDN BHD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SUMMIT HELICOPTERS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION INTERIOR SERVICES INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JETEXE AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'C & M  MARINE AVIATION SERVICES INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION & ELECTRONICS SUPPORT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'K.M.R. AVIATION SERVICES, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'COX ENTERPRISES, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CAMTRONICS, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ISLENA DE INVERSIONES S.A.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PIPER AIRCRAFT INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DYNAMIC AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'KEY LIME AIR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AERMECCANICA', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ESSEX AERO SERVICES, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AKIMA LOGISTICS SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CITY JET DAC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EXELON CORPORATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Aramco Services Co.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TYCO ELECTRONICS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'IAPSCO LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SKYLINK INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JET AVIONICS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JETPOWER', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PERFORM AIR INTERNATIONAL INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HILL AIR CORPORATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Jet Spares Int\'l Pty Ltd', 'icao' => 'ZZZZZ'],
            ['company_name' => 'QAI AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROSPACE SUPPORT ASSOCIATES LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FAR EAST HYDROFOIL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AERONATE INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'UNITED TECHNOLOGIES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BUSINESS JET ACCESS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PREFERRED AIRPARTS LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TOTAL AIRCRAFT PARTS, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRMAURIN INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TULSAIR BEECHCRAFT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Sky Prime Aviation Services', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AERIA LUXURY INTERIORS LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WEST STAR AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ATLAS AEROSPACE ACCESSORIES, I', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TRINITY AIR AMBULANCE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WYATT AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIR TRANSPORT COMPONENTS, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'XOJET', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MARITIME AEROSPACE AG', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EXECUTIVE AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ZEEFAX, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ITS INFINITY TRADING & SOLUTIONS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PSI', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SECAMIC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AAF SPARES LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DONE AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JETPRO', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRBORNE PRODUCT SUPPORT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRCRAFT TECHNICAL SERVICES INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AERO SUPPLIES INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MIAMI AIR INTERNATIONAL INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MOTORFLUG BADEN-BADEN GmbH', 'icao' => 'ZZZZZ'],
            ['company_name' => 'YAS INTERNATIONAL DIST INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DAVENPORT AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'First Class Air Support', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MIAMI TECH', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FLIGHT EQUIPMENT INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TRADE AIR, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JVAEROSERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'COMMERCIAL AVIATION INT\'L', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JSC \'MOTOR SICH\'', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DRAKE AIR INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GELBYSON SRL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'NFF AVIONICS SERVICES INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HELICOPTER SPECIALTIES, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TOTAL AVIATION SOLUTIONS PTE LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GENERAL AIRFRAME SUPPORT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION REPAIR TECH, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FLYING COLOURS CORP-KSUS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EXECUTIVE JET MAINTENANCE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIR PALACE CO., LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FIRST CLASS AIR REPAIR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Northrop Grumman', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Air Service International AS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'THREE WING FLYING SERVICES, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FLIGHT SAFETY SERVICES CORPORATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DAKOTA AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WESTERN JET AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DAVIS AVIATION, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BERTRAM SEARS INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION EXCESS INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRWAY AEROSPACE, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EXODUS AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PACIFIC SOUTHWEST INSTRUMENTS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PRECISION AVIATION GROUP', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TOUCAN AIR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ATELIERS BIGATA', 'icao' => 'ZZZZZ'],
            ['company_name' => 'INAV LLC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Leki Aviation', 'icao' => 'ZZZZZ'],
            ['company_name' => 'C & L AVIATION SERVICES, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Calm Air International LP', 'icao' => 'ZZZZZ'],
            ['company_name' => 'IPCO', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Helicopter Parts Int\'l., Inc.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'A & R AVIATION SERVICE, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Aero Accessories & Repair, Inc', 'icao' => 'ZZZZZ'],
            ['company_name' => 'KP AVIATION, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SKY SHUTTLE/SKY TECH ENGI', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TRONAIR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION SPARES DISTRIBUTION GMBH', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVAIR EXPENDABLES INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROTRANSCARGO FZE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TWIN OTTER INTERNATIONAL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FLORIDA AERO PAINT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FLIGHT LINE PRODUCTS, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'RAINBOW AIR INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BOARD OF POLICE COMMISSIONERS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'RELIABLE JET MAINTENANCE LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIR TRANSPORT INT\'L INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SITA AIR (P) LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'RGB ENTERPRISES, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SPECTRA JET', 'icao' => 'ZZZZZ'],
            ['company_name' => 'IFR PRECISION INSTRUMENTS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'COMMUTAIR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EirTrade Aviation Ireland Ltd', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SKF Limited', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MIDEAST AIRCRAFT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TABY AIR MAINTENANCE AB', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AZ JET SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MAG AEROSPACE CANADA CORP', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SATENA', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EAGLE AIR MED', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AOG Logistics', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Yurim Technology Co.,Ltd.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ESTERLINE CORPORATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DAVID MARTIN', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ARRAY SPARES,LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BURLINGTON  AIR CENTER', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ADVANCED HELICOPTER SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MULTIFLIGHT LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AERODIRECT INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'RCO Aerospace Products, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'POLLARD AIRCRAFT SALES, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BLOUNT BROS. CONSTRUCTION LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CETIM SUD-OUEST', 'icao' => 'ZZZZZ'],
            ['company_name' => 'IKM INSTRUTEK AS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'VANTAGE AIR SUPPORT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CAPE AEROSPACE REPAIR SERVICE, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ACTC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EASYFLY S.A.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SUNDANCE HELICOPTERS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PAC SEATING SYSTEMS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRWAYS AERO ASSOCIATIONS LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'RUSH AVIATION SERVICES, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HELLENIC AEROSPACE INDUSTRY S.A.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WESTERN AIR LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'VBR TURBINE PARTNERS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TECNICAS Y SERVICIOS DE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CB AVIATION, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'COMPRESSED GAS SYSTEMS, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CAVU AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'REUT AIRWAYS LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'THE FLYING BULLS GMBH', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HELI UNION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ICARUS INTERNATIONAL GROUP, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TIC AEROSPACE, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PARTS & SPARES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'LINK SOLUTIONS GROUP LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'INTERGLOBE AVIATION LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Heli-One (Norway) AS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JET AIR, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BUDAPEST AIRCRAFT SERVICE KFT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'RANGER AIR AVIATION LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SOCIETE AEROPARTS MAINTENANCE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HORIZON AERO SERVICES, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Central Point Procurement, Inc', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SOUTHEAST AEROSPACE INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PREMIER AIR, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MARTIN SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION ENTERPRISES, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Temco Ltd.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CHROMALLOY MATERIAL SOLUTIONS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CORPORATE FLIGHT MANAGEMENT, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MICRO PRECISION CALIBRATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Teollisuuden Voima Oyj', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TRESCAL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIR STATION AVIATION INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Leading Edge Aviation, Inc.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRBORNE SYSTEMS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MERIDIANA MAINTENANCE  S.P.A.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PRECISION TECH AERO, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ALTAMONT AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ICARIUS AEROTECHNICS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROLITORAL S.A. DE C.V.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GRIFFING FLYING SERVICES INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CRAIG AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AXPO AG', 'icao' => 'ZZZZZ'],
            ['company_name' => 'XTRA AEROSPACE, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'INTERCOPTER GMBH', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ACIA AERO PARTS COMPANY SAS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Elite Aerospace', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROSPACE MAINTENANCE SOLUTIONS, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SOURCE ONE SPARES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EMERSON ELECTRIC CO.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'OHIO UNIVERSITY AVIONICS ENGINEERING CENTER', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GOAL AVIATION LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HELI ALL INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JJ AERONAUTICS INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MBI LEASING, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'VICAVIONICS SA DE CV', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TRADEWINDS AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'NORTH CAROLINA DEPARTMENT OF TRANSPORTATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'R&C AVIATION , INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'EMERY AIR, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVFLEX CORP.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'DENVER AIR SUPPORT, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AVIATION MINING SOLUTION, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TRANSCAT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'STAPLEFORD FLYING CLUB LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HAITEC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'NRG', 'icao' => 'ZZZZZ'],
            ['company_name' => 'STANDARD AERO BUSINESS AVIATION SERVICES, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SCAN SUPPORT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MOOG', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AECO AIRCRAFT ENGINES & COMPONENTS CORP', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SKY-N-SEA INTERNATIONAL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AMERISTAR JET CHARTER INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HEXCEL CORPORATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ELITE JET SERVICE GMBH', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BRAZILIAN AERONAUTICAL COMMISSION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WASTETRANS LLC DBA DISCOUNT AERO PARTS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'RED WING AEROPLANE COMPANY', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JET ONE AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FLUGEL, LLC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'S J CONTRACTING SERVICES LTD t/a HELI-LIFT SERVICE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CTT SYSTEMS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WESCO AIRCRAFT', 'icao' => 'ZZZZZ'],
            ['company_name' => 'RANGER AIR', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Sojitz Aerospace', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SILVER WINGS AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TOUCHPOINT AVIATION SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'JR AEROPARTS, CORP', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROSPACE PARTS TRADING-IRELAND LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BLUE AIR AVIATION S.A.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BEACH AVIATION GROUP, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ASSOCIATED SALES INTERNATIONAL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ARIA ENGENHARIA E MANUTENCAO DE AERONAVES LTDA -ME', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIRCRAFT BELTS, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SUN AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SPRINTAIR SA', 'icao' => 'ZZZZZ'],
            ['company_name' => 'LAMAR AERO, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GLOBAL TECHNIK CORP', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ELECTRONIC SOURCE COMPANY', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SEANAE INTERIORS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Westcoast Energy Inc.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'VIP AERO (LUXEMBOURG) SARL', 'icao' => 'ZZZZZ'],
            ['company_name' => 'VIRGINIA STATE POLICE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'OLYMPIC TRADING LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SIMTECH, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TT Electronics', 'icao' => 'ZZZZZ'],
            ['company_name' => 'SEATTLE AIRCRAFT RENTALS LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Performance Repair Group, LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TRANSPORT CANADA AIRCRAFT SERV', 'icao' => 'ZZZZZ'],
            ['company_name' => 'Turner Aviation', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TANDEM AVIATION INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PIAGGIO AMERICA INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'WUHAN HANGDA AERO SCIENCE & TECHNOLOGY', 'icao' => 'ZZZZZ'],
            ['company_name' => 'VELOCITY AEROSPACE - BURBANK', 'icao' => 'ZZZZZ'],
            ['company_name' => 'R & R SERVICES', 'icao' => 'ZZZZZ'],
            ['company_name' => 'TUBREAUX AVIATION MAINTENANCE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'PARAGON AIRCRAFT SERVICE, INC.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'STELIA AEROSPACE', 'icao' => 'ZZZZZ'],
            ['company_name' => 'IDENTIPARTS LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'HELENA AIRCRAFT, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MSP', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GLOBAL AVIATION + PIPER PARTS GMBH', 'icao' => 'ZZZZZ'],
            ['company_name' => 'ESTAFETA CARGA AEREA, SA DE CV', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GEI Industries Inc.', 'icao' => 'ZZZZZ'],
            ['company_name' => 'KCAC AVIATION LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GOLD AVIATION SERVICES/DOLPHIN ATLANTIC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'INTERJET AVIATION', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MULTI TRADING CORP', 'icao' => 'ZZZZZ'],
            ['company_name' => 'KELLSTROM DEFENSE AEROSPACE, INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'MILFORD POWER', 'icao' => 'ZZZZZ'],
            ['company_name' => 'NAIZAK GLOBAL ENGINEERING', 'icao' => 'ZZZZZ'],
            ['company_name' => 'FIELDTECH AVIONICS & INSTRUMENTS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'GADRINGER-GURTE GMBH', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CFM INTERNATIONAL INC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BRISTOW HELICOPTERS LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AL JABER AVIATION LLC', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AIP SAS', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BCGNEEDS COMPANY', 'icao' => 'ZZZZZ'],
            ['company_name' => 'CHOCTAW IKHANA LABORATORY SERV', 'icao' => 'ZZZZZ'],
            ['company_name' => 'AEROTECH AIRCRAFT MAINTENANCE LTD', 'icao' => 'ZZZZZ'],
            ['company_name' => 'BIGHORN AIRWAYS', 'icao' => 'ZZZZZ'],
        ]);
	}
}
